apiVersion: v1
kind: Service
metadata:
  name: next-app-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # optional, default classic LB
spec:
  type: LoadBalancer
  selector:
    app: next-app
  ports:
    - port: 80        # external port
      targetPort: 3000 # container port
