name: CI/CD

# Trigger on push to main (change branch as needed)
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      # 3️⃣ Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4️⃣ Build Docker image (amd64 for EKS)
      - name: Build & Push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker buildx build \
            --platform linux/amd64 \
            -f src/Dockerfile \
            -t ${{ secrets.ECR_REPO }}:$IMAGE_TAG \
            -t ${{ secrets.ECR_REPO }}:latest \
            --push .

      # 5️⃣ Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0' # match your cluster version

      # 6️⃣ Update kubeconfig for EKS
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name cicd-next-cluster   # 👈 replace with your EKS cluster name

      # 7️⃣ Update EKS deployment with new image
      - name: Update Kubernetes deployment
        run: |
          IMAGE_TAG=${{ github.sha }}
          kubectl set image deployment/next-app next-app=${{ secrets.ECR_REPO }}:$IMAGE_TAG
          kubectl rollout status deployment/next-app
